# version: '3.8'

networks:
  web_network:
    external: true

volumes:
  pg_data:

services:
  django_bright:
    build: .
    container_name: bright_app
    image: bright_django:latest
    command: python3 manage.py runserver  0.0.0.0:8000 --insecure
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8010:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - pgsql
    networks:
      - web_network

  pgsql:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: bright_db
      POSTGRES_USER: bright_user
      POSTGRES_PASSWORD: bright_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - web_network
